#!/bin/bash

# List of servers
servers=("10.23.93.108" "10.23.93.93" "10.23.94.48" "10.23.93.22" "10.23.51.9" "10.22.60.10" "10.23.94.33" "10.23.93.33" "10.23.93.109" "10.23.94.18" "10.23.93.90")

# Cron job to add
cron_job="0 * * * * /OS_REPO/DiskUsageMailAlert.sh"

# Loop through each server
for server in "${servers[@]}"; do
    # Check if the cron job is already present in the crontab
    cron_check=$(ssh root@$server "crontab -l | grep -F '$cron_job'")
    
    # If not present, append the cron job
    if [[ -z "$cron_check" ]]; then
        echo "Adding cron job to $server"
        ssh root@$server "echo '$cron_job' >> /var/spool/cron/crontabs/root"
    else
        echo "Cron job already exists on $server"
    fi
done

echo "Cron job has been added (if not already present) to all listed servers."
